[package]
name = "bvh"
description = "A fast BVH using SAH"
version = "0.2.1"
authors = [
    "Sven-Hendrik Haase <svenstaro@gmail.com>",
    "Alexander Dmitriev <alexander.dmitriev2580@gmail.com>"
]
readme = "README.md"
repository = "https://github.com/svenstaro/bvh"
documentation = "https://docs.rs/crate/bvh"
keywords = ["bvh", "bounding", "volume", "sah", "aabb"]
license = "MIT"

[dependencies]
approx = "0.1.1"
nalgebra = "0.12.1"
rand = "0.3.14"
log = "0.3.7"
stdsimd = "*"

[dev-dependencies]
quickcheck = "0.4.1"
obj-rs = "0.4"

[profile.bench]
debug = true
lto = true
